apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: sync-controller
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-controller
  namespace: system
  labels:
    control-plane: sync-controller
spec:
  selector:
    matchLabels:
      control-plane: sync-controller
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: sync-controller
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: squaremo/sync-controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 10
