# permissions for end users to edit proxysyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxysync-editor-role
rules:
- apiGroups:
  - sync.fluxcd.io
  resources:
  - proxysyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sync.fluxcd.io
  resources:
  - proxysyncs/status
  verbs:
  - get
