# permissions for end users to view proxysyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxysync-viewer-role
rules:
- apiGroups:
  - sync.fluxcd.io
  resources:
  - proxysyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sync.fluxcd.io
  resources:
  - proxysyncs/status
  verbs:
  - get
