# permissions for end users to view remotesyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remotesync-viewer-role
rules:
- apiGroups:
  - sync.fluxcd.io.fluxcd.io
  resources:
  - remotesyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sync.fluxcd.io.fluxcd.io
  resources:
  - remotesyncs/status
  verbs:
  - get
