
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - sync.fluxcd.io
  resources:
  - syncgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sync.fluxcd.io
  resources:
  - syncgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sync.fluxcd.io
  resources:
  - syncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sync.fluxcd.io
  resources:
  - syncs/status
  verbs:
  - get
  - patch
  - update
