# permissions for end users to edit syncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sync-editor-role
rules:
- apiGroups:
  - sync.fluxcd.io
  resources:
  - syncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sync.fluxcd.io
  resources:
  - syncs/status
  verbs:
  - get
