# permissions for end users to edit syncgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syncgroup-editor-role
rules:
- apiGroups:
  - sync.fluxcd.io.fluxcd.io
  resources:
  - syncgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sync.fluxcd.io.fluxcd.io
  resources:
  - syncgroups/status
  verbs:
  - get
