apiVersion: sync.fluxcd.io/v1alpha1
kind: Sync
metadata:
  name: sync
spec:
  url: "http://source-controller.system/gitrepository/default/source/latest.tar.gz"
  paths:
  - config/ollehworld
  interval: 1m
